config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


 resources :riders do
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create]
end
  root 'riders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :rider
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :rider
  belongs_to :user
  validates_uniqueness_of :rider_id, scope: :user_id
end

app/models/rider.rb
class Rider < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :riders, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :liked_riders, through: :likes, source: :rider
         has_many :comments, dependent: :destroy
         def already_liked?(rider)
    self.likes.exists?(rider_id: rider.id)
  end     
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      rider = Rider.find(params[:rider_id])
      comment = rider.comments.build(comment_params) 
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) 
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) 
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(rider_id: params[:rider_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(rider_id: params[:rider_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    if params[:search] != nil && params[*:search] != ''
       search = params[:search]
       @riders = Rider.joins(:user).where("name LIKE ?", "%#{search}%")
    else
       @riders = Rider.all
      end
  end
  def new
    @riders = Rider.new
  end
    
  def create
    rider = Rider.new(rider_params)
    rider.user_id = current_user.id
  if rider.save!
    redirect_to :action => "index"
  else
    redirect_to :action => "new"
  end
end

  def show
    @rider = Rider.find(params[:id])
    @comments = @rider.comments
       @comment = Comment.new
   end
    
    
  private
    def rider_params
      params.require(:rider).permit(:name, :title, :image, :about, :user_id)
    end
  end    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>HEISEI KAMEN RIDER</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 
</head>

<body>
  <header>
  <img src="../../../assets/rogo.jpg" width="80px" height="80px"> 
  <h1 class="title">HEISEI KAMEN RIDER</h1>
  <div class="header-list">
    <ul>
      <li><%= link_to "ログイン", riders_path %></li>
      <li><%= link_to "新規",new_rider_path %></li>
    
      </ul>
    </div>
  </header>
  <main>
    <%= yield %>
  </main>
  <footer>
  <p>Copyright © GeekSalon All Rights Reserved.</p>
</footer>
  </body>
</html>

app/views/layouts/new.html.erb
<!DOCTYPE html>
<html>

app/views/riders/index.html.erb
<body class="haikei1">

<h3>投稿一覧</h3>

<div class="kennsaku">
 <%= form_tag({controller:"riders",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する' %>
<% end %>

<%= button_to "新規投稿へ", new_rider_path, method: :get %>
</div>

<div class="riders-container">
    <% @riders.each do |t| %>
        <div class="riders-box">
            <P class="W"><%= t.user.email %></p>
            <%= image_tag t.image_url, size: "340x350" if t.image? %>
          <div class="uratarosu" >
            <p class="another"><%= t.name %></P>
          <div class="kintarosu">  
            <%= link_to "詳細へ", rider_path(t.id) %>
            <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
                <%= button_to rider_like_path(id: t.id, rider_id: t.id), method: :delete do %>
                    <p>いいねを取り消す</p><%= t.likes.count %>
                <% end %>
            <% else %>
                <%= button_to rider_likes_path(id: t.id, rider_id: t.id), method: :post do %>
                    <p>いいね</p><%= t.likes.count %>
                <% end %>
            <% end %>
        <% else %>
            <p>いいねの数 = </p><%= t.likes.count %>
        <% end %>
        </div>
        </div>
            <p class="ryutarosu"><%= t.title %></P>
            
            
        </div>
     <% end %>
</div>
</body>

app/views/riders/new.html.erb
<body class="haikei2">
  <%= form_for @riders do |f| %>

    <div class="post-container">
    <p class="title">お気に入りのライダーを投稿しよう</p>
      <%= f.label :名前 %>
      <%= f.text_field :name, :size => 60 %>

      <%= f.label :作品名 %>
      <%= f.text_field :title, :size => 60 %>

      <%= f.label :キャラクター詳細 %>
      <%= f.text_field :about, :size => 60 %>
    
     <div class="field">
      <%= f.label :画像 %>
      <%= f.file_field :image %>
     </div>
     <%= f.submit "投稿する", class: "mofmof" %>
     <% end %>
     </div>


    

  <%= link_to "一覧に戻る", riders_path %>
</body>

app/views/riders/show.html.erb
<body class="haikei3">
<h1><p class="dennou"><%= @rider.title  %></p></h1>


<div class="rider">

<%= image_tag @rider.image_url, size: "400x350" if @rider.image? %>
<p class="kuuga"><%= @rider.about %></p>
  
</div>
<div class="agito">
<p class="toukoubi"><%= @rider.created_at %></p>
  
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@rider) %>
        <%= button_to rider_like_path(@rider), method: :delete do %>
          <p>いいねを取り消す</p><%= @rider.likes.count %>
        <% end %>
      <% else %>
        <%= button_to rider_likes_path(@rider), method: :post do %>
          <p>いいね</p><%= @rider.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = <%= @rider.likes.count %></p>
    <% end %>
  <%= button_to "編集する", edit_rider_path(@rider.id) %>
</div>

<div class="ryuki">
<h2>いいねしたユーザー</h2>
<% @rider.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
</div>      
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@rider, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= submit_tag "コメントする" %>
    <% end %>
  <% end %>
</div>

<%= link_to "ライダー一覧に戻る", riders_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>